"""Public API for the simulated orchestrator slice."""

from .adapters import (
    AuditSink,
    CameraRepository,
    InMemoryAuditSink,
    InMemoryCameraRepository,
)
from .asset_inventory import (
    AssetChangeState,
    AssetInventoryOutcome,
    AssetInventoryService,
    AssetRecord,
    AssetRepository,
    AssetSummary,
    AssetType,
    InMemoryAssetRepository,
    asset_list_manifest,
    asset_outcome_to_contract,
)
from .contracts import CommandRejectedError, ContractValidator
from .detection import TemporalPersonConfirmer
from .device_gateway import (
    DeviceCancelGateway,
    DeviceTextCommandGateway,
    DeviceTextCommandRejectedError,
)
from .discovery import (
    DiscoveryCandidate,
    DiscoveryJob,
    DiscoveryOutcome,
    InMemoryPassiveDiscoverySource,
    PassiveDiscoveryService,
    PassiveDiscoverySource,
    discovery_candidate_to_contract,
    discovery_outcome_to_contract,
    passive_discovery_manifest,
)
from .models import (
    AuditEvent,
    CameraRecord,
    CameraState,
    CameraStatus,
    CommandOutcome,
    ExecutionContext,
    ExecutionStatus,
)
from .monitoring_adapters import (
    EventSink,
    FrameSource,
    InMemoryEventSink,
    InMemoryFrameSource,
    InMemoryNotificationSink,
    NotificationSink,
)
from .monitoring_models import (
    FrameObservation,
    JobState,
    JobTransition,
    MonitoringOutcome,
    Notification,
    NotificationChannel,
    PersonDetectedEvent,
)
from .monitoring_service import (
    MonitoringService,
    camera_monitor_manifest,
    monitoring_outcome_to_contract,
    notification_to_contract,
    person_event_to_contract,
    transition_to_contract,
)
from .service import (
    CameraStatusService,
    audit_to_contract,
    camera_status_manifest,
    outcome_to_contract,
)
from .state_machine import InvalidTransitionError, MonitoringJob
from .voice_gateway import (
    CameraAliasResolver,
    ExactVoiceIntentExtractor,
    FixtureSpeechToText,
    ProposedVoiceIntent,
    TranscriptionContractValidator,
    VoiceCommandRejectedError,
    VoiceMonitoringGateway,
)

__all__ = [
    "AssetChangeState",
    "AssetInventoryOutcome",
    "AssetInventoryService",
    "AssetRecord",
    "AssetRepository",
    "AssetSummary",
    "AssetType",
    "AuditEvent",
    "AuditSink",
    "CameraAliasResolver",
    "CameraRecord",
    "CameraRepository",
    "CameraState",
    "CameraStatus",
    "CameraStatusService",
    "CommandOutcome",
    "CommandRejectedError",
    "ContractValidator",
    "DeviceCancelGateway",
    "DeviceTextCommandGateway",
    "DeviceTextCommandRejectedError",
    "DiscoveryCandidate",
    "DiscoveryJob",
    "DiscoveryOutcome",
    "EventSink",
    "ExactVoiceIntentExtractor",
    "ExecutionContext",
    "ExecutionStatus",
    "FixtureSpeechToText",
    "FrameObservation",
    "FrameSource",
    "InMemoryAssetRepository",
    "InMemoryAuditSink",
    "InMemoryCameraRepository",
    "InMemoryEventSink",
    "InMemoryFrameSource",
    "InMemoryNotificationSink",
    "InMemoryPassiveDiscoverySource",
    "InvalidTransitionError",
    "JobState",
    "JobTransition",
    "MonitoringJob",
    "MonitoringOutcome",
    "MonitoringService",
    "Notification",
    "NotificationChannel",
    "NotificationSink",
    "PassiveDiscoveryService",
    "PassiveDiscoverySource",
    "PersonDetectedEvent",
    "ProposedVoiceIntent",
    "TemporalPersonConfirmer",
    "TranscriptionContractValidator",
    "VoiceCommandRejectedError",
    "VoiceMonitoringGateway",
    "asset_list_manifest",
    "asset_outcome_to_contract",
    "audit_to_contract",
    "camera_monitor_manifest",
    "camera_status_manifest",
    "discovery_candidate_to_contract",
    "discovery_outcome_to_contract",
    "monitoring_outcome_to_contract",
    "notification_to_contract",
    "outcome_to_contract",
    "passive_discovery_manifest",
    "person_event_to_contract",
    "transition_to_contract",
]
